### ISSUE TITLE
Update Instructions Re: INSTALLED_APPS

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#13]
Hello!

 I put the `'wagtail_content_import' and 'wagtail_content_import.pickers.google'` at the end of my list of installed apps, and the override for the `extra_footer_actions` was not kicking in.  I had to add it to INSTALLED_APPS *before* `wagtail.admin` to get it to appear.  Might be worth updating the README to that effect. :) . Cheers!

**Comment by jacobtoppm** [comment]
Hi! That's a good point, thanks for bringing it up - I've added it in #17 .

**Comment by cyface** [comment]
@jacobtoppm Looks good now!
