### ISSUE TITLE
Example for Content Fields

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#14]
Hello! 

 It took me a bit to realize that what needed to be in the mapper was the name of the field on the model that mapped to the type of block.  The sample values make it look like it's the ClassName of the block, but it's actually the field_name.

```
class GoogleImportMapper(StreamFieldMapper):
    html = RichTextConverter("paragraph")
    image = ImageConverter("image_block")
    heading = TextConverter("paragraph")
    table = TableConverter("table")
```

I think it might be worth updating the README to go into a bit more detail about what value goes in there. :)

Cheers!

**Comment by jacobtoppm** [comment]
Hello! Yes, I can definitely see how that can cause confusion. I've added an explicit StreamField setup example in #17 , which I hope clarifies things a bit more - thanks for bringing this up.

**Comment by cyface** [comment]
@jacobtoppm Much clearer now, thank you!
