### ISSUE TITLE
Shared Drives Support

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#15]
I am not able to see gdocs that are in team (aka 'shared') drives.  I may be as simple as implementing `supportsAllDrives=true` as described here: 

https://developers.google.com/drive/api/v3/enable-shareddrives

...but...it might be more involved than that.

**Comment by cyface** [comment]
@jacobtoppm Do I need to add some additional permissions to get this to work? I still am only seeing a list of my local files in the picker window...

**Comment by cyface** [comment]
Looks like this works via search - you have to be logged into your team google account, and they search for Docs - which does work! You just can't browse down to your doc.

**Comment by jacobtoppm** [comment]
In version 0.2.2, I've implemented shared navigation as a separate tab/view in the picker, to ensure that documents simply in My Drive are also accessible. Let me know if this works for you!

**Comment by cyface** [comment]
0.2.2 Looks good.  Closing this!
