### ISSUE TITLE
Image Import With Custom Image Model

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#16]
Hello! I have a Custom Image model like this:

```
class CustomImage(AbstractImage):
    # eg. To add a caption field:
    caption = models.CharField(max_length=255, blank=True)

    admin_form_fields = Image.admin_form_fields + ("caption",)


class CustomRendition(AbstractRendition):
    image = models.ForeignKey(
        CustomImage, on_delete=models.CASCADE, related_name="renditions"
    )

    class Meta:
        unique_together = (("image", "filter_spec", "focal_point_key"),)
```

That is pointed at by the `WAGTAILIMAGES_IMAGE_MODEL` setting.

I have an ImageBlock like this:

```
class ImageBlock(StructBlock):
    """
    Image selection within body content
    """

    show_full_image = BooleanBlock(required=False)
    image = ImageChooserBlock()

    class Meta:
        icon = "image / picture"
        admin_text = mark_safe("<b>Image Block</b>")
        label = "Image Block"
        template = "pages/blocks/image_block.html" 
```

Article Model like this:

```
class BasePage(ContentImportMixin, Page):
    body = StreamField(BaseBodyStreamBlock)
```

And BaseBodyStreamBlock:

```
class BaseBodyStreamBlock(StreamBlock):
    image_block = ImageBlock(
        help_text="Designed to be used within the main article body content"
    )
```

And I set up the mapper like this:

```
class GoogleImportMapper(StreamFieldMapper):
    html = RichTextConverter("paragraph")
    image = ImageConverter("image_block")
    heading = TextConverter("paragraph")
    table = TableConverter("table")
```

When I run the Google Docs import, it seems to go fine, but then when it actually tries to render the create page view with the content in it, it fails with:
```
'CustomImage' object has no attribute 'get'
```

Fail is on line 94 of ```wagtail.core.blocks.struct_block.py```:

```
 bound_child_blocks = collections.OrderedDict([
            (
                name,
                block.bind(value.get(name, block.get_default()),
                           prefix="%s-%s" % (prefix, name), errors=error_dict.get(name))
            )
            **for name, block in self.child_blocks.items() …**
        ])
        return {
            'children': bound_child_blocks,
            'help_text': getattr(self.meta, 'help_text', None),
            'classname': self.meta.form_classname,
```

The html/RichTextBlocks seem to import fine, but this image one has the issue.  I know that Extending the Image model is always a fun time, but I am not clear where I need to adjust things here. :) . Thank you!

**Comment by jacobtoppm** [comment]
Hello! In this case, it's an issue with how you've set up the mapper: ImageConverter assumes your block is a simple ImageChooserBlock, whereas your image block is a custom StructBlock, containing a BooleanBlock and an ImageChooserBlock. This just requires a bit more setup (there's a section in the README on importing StructBlocks): writing a custom converter.

I tried your custom image model, and was able to get the following converter working:

`from wagtail_content_import.mappers.converters import BaseConverter, ImageConverter

class ImageBlockConverter(BaseConverter):
    def __call__(self, element, user, *args, **kwargs):
        image_url = element['value']
        image_name, image_content = ImageConverter.fetch_image(image_url)
        image = ImageConverter.import_as_image_model(image_name, image_content, owner=user)
        return (self.block_name, {'show_full_image': None, 'image': image})`

If you add this custom converter, then replace your:

`image = ImageConverter("image_block")`

With:

`image = ImageBlockConverter("image_block")`

Let me know if this helps!

**Comment by zerolab** [comment]
@jacobtoppm the above looks like a prime candidate for some recipes. Possibly as a wiki page on the repo to start with

**Comment by cyface** [comment]
@jacobtoppm Thank you! That worked perfectly! I agree with the recipe comment. :)

**Comment by jacobtoppm** [comment]
Great, glad that worked! I'm currently working on better documentation - using mkdocs rather than just a readme - so I'll add a recipes section to that.
