### ISSUE TITLE
Django 3 Compatibility

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#24]
Hello! Looks like this import needs to be tweaked to work with Django 3:  https://github.com/torchbox/wagtail-content-import/blob/35fa3955d3f9f2275c598382c92a48e324e35883/wagtail_content_import/wagtail_hooks.py#L1

I believe that changing the import to `from django.templatetags.static import static` should be compatible quite a few versions back.

**Comment by jacobtoppm** [comment]
This should be resolved in 0.2.4, and by this PR: https://github.com/torchbox/wagtail-content-import/pull/26
