### ISSUE TITLE
Don't Explode if Google Keys Not Set

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#27]
Hello - right now, the edit page throws a 500 if the GOOGLE_AUTH_CLIENT_CONFIG and GOOGLE_PICKER_API_KEY are not set.

Could we make this a little more robust, and just not do anything if those are not set, or set to ""?

We have lots of envs where we may not want to run this (e.g. local dev envs) and don't want everyone to have to have these keys defined and working.  I can set it to a shell of the JSON, but then it loads and just throws a .js error.

Thank you!

**Comment by jacobtoppm** [comment]
This should be fixed in version `0.3.0`, which simply doesn't register the picker if config variables aren't provided or are empty. Let me know if this doesn't fix the issue!
