### ISSUE TITLE
Make Settings Specific

### ISSUE THREAD

**Issue by cyface** [torchbox/wagtail-content-import#28]
Hello!

 The `GOOGLE_OAUTH_CLIENT_CONFIG `and `GOOGLE_PICKER_API_KEY `settings don't mention this project at all...and in a larger project, we might (and do) have a number of Google keys for various integrations.

 I'm wondering if we can name these settings in such a way as to make it clear they are used for this project?

 `WAGTAIL_CONTENT_IMPORT_GOOGLE_OAUTH_CLIENT_CONFIG` is long, but might be the most clear. :)  Same with `WAGTAIL_CONTENT_IMPORT_GOOGLE_PICKER_API_KEY`.

Thank you!

**Comment by jacobtoppm** [comment]
Hello! This has been changed to the `WAGTAIL_CONTENT_IMPORT_` prefix in version `0.3.0`, which should hopefully fix this issue.
