### ISSUE TITLE
Compatibility issues with Wagtail 6.0

### ISSUE THREAD

**Issue by drimacus182** [torchbox/wagtail-content-import#60]
### Issue summary

After upgrading to Wagtail 6.0 import action buttons are poorly rendered (see the screenshot)
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

<img width="996" alt="screenshot" src="https://github.com/torchbox/wagtail-content-import/assets/3090883/236da501-55a8-42e4-90cb-5713750717b4">

### Technical details

-   Python version: 3.11.5
-   Django version: 5.0.2
-   Wagtail version: 6.0
-   Browser version: Firefox 122

**Comment by SaiGanesh21** [comment]
Hi @drimacus182, 
I would like to work on this issue. Could you please elaborate on what the action buttons here mean exactly?

**Comment by drimacus182** [comment]
Works fine with: `wagtail==6.0.2` and `wagtail-content-import==0.12`
So I think this issue could be closed now
